# Generated by Django 4.2.5 on 2023-09-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lessonview_viewed_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
