# Generated by Django 4.2.5 on 2023-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lesson_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(related_name='lessons', to='app.product'),
        ),
    ]
