# Generated by Django 4.2.5 on 2023-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_lesson_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonview',
            old_name='viewed_time_seconds',
            new_name='current_position',
        ),
        migrations.RemoveField(
            model_name='lessonview',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lessonview',
            name='watched_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
