# Generated by Django 4.2.5 on 2023-09-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_viewed_time_seconds_lessonview_current_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonview',
            old_name='current_position',
            new_name='current_position_sec',
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='app.lesson'),
        ),
    ]
