# Generated by Django 4.2.5 on 2023-09-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_current_position_lessonview_current_position_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccess',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='app.product'),
        ),
    ]
